name: build-and-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: syohdev/hello-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 불변 태그: 날짜+짧은 SHA
      - name: Set immutable tag
        id: tag
        run: |
          TS=$(date -u +'%Y%m%d%H%M%S')
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG=${TS}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # M1/M2에서도 Azure 쪽과 호환되도록 linux/amd64로 빌드
      - name: Build and push (immutable tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
          # latest는 옵션. 원하면 추가:
          # ${{ env.IMAGE_NAME }}:latest

      # Web App 컨테이너 이미지 설정을 "해당 태그"로 갱신
      - name: Deploy to Azure Web App (container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: index.docker.io/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
