name: Deploy nginxdemo to Azure Web App (Container)

on:
  push:
    branches: [ "main" ]   # main 푸시 시 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 포털에서 "코드형"이 아니라 "컨테이너형" Web App 이어야 함
      # Publish Profile로 인증하고, App Service의 컨테이너 이미지를 지정
      - name: Deploy container image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "kt00-day2-ci-cd"   # 예: kt00-ci-cd-nginx
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: index.docker.io/nginxdemos/hello:latest
